[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "extra-streamlit-components>=0.1.81",
    "jpholiday>=1.0.2",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "python-dateutil>=2.9.0.post0",
    "reportlab>=4.4.6",
    "streamlit>=1.52.1",
]
